name: Go Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.x']
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Install Dependencies
        run: |
          go get github.com/go-redis/redis/v8
          go get -u github.com/gin-gonic/gin
          go get github.com/stretchr/testify
          go get github.com/itchyny/base58-go/cmd/base58

